# Cloud Build configuration for automatic deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/news-platform-api:latest', '.']
    
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/news-platform-api:latest']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'news-platform-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/news-platform-api:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NEWSAPI_KEY=${_NEWSAPI_KEY},OPENAI_API_KEY=${_OPENAI_API_KEY},DEBUG=False'

images:
  - 'gcr.io/$PROJECT_ID/news-platform-api:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
